# Generated by Django 6.0.5 on 2026-05-09 18:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicField',
            fields=[
                ('academic_field_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(help_text='Nombre del campo académico (ej. Ingeniería de Sistemas)', max_length=200, unique=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Campo Académico',
                'verbose_name_plural': 'Campos Académicos',
                'db_table': 'academic_field',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Degrees',
            fields=[
                ('degree_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(max_length=100, unique=True, verbose_name='Grado Académico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Grado Académico',
                'verbose_name_plural': 'Grados Académicos',
                'db_table': 'degrees',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(max_length=100, unique=True, verbose_name='Idioma')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
                'db_table': 'languages',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(max_length=100, unique=True, verbose_name='Habilidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'db_table': 'skill',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='AcademicHistory',
            fields=[
                ('academic_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('institution_name', models.CharField(max_length=255, verbose_name='Nombre de la Institución')),
                ('speciality', models.CharField(blank=True, max_length=200, null=True, verbose_name='Especialidad/Mención')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('academic_field_id', models.ForeignKey(db_column='academic_field_id', on_delete=django.db.models.deletion.PROTECT, to='core.academicfield', verbose_name='Campo Académico')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='academic_histories', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('degree_id', models.ForeignKey(db_column='degree_id', on_delete=django.db.models.deletion.PROTECT, to='core.degrees', verbose_name='Grado')),
            ],
            options={
                'verbose_name': 'Historial Académico',
                'verbose_name_plural': 'Historiales Académicos',
                'db_table': 'academic_history',
                'ordering': ['-start_date', 'user_id'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperiences',
            fields=[
                ('work_experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('enterprise_name', models.CharField(max_length=255, verbose_name='Nombre de la Empresa')),
                ('responsibilities', models.TextField(blank=True, null=True, verbose_name='Responsabilidades')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción general')),
                ('achievement', models.TextField(blank=True, null=True, verbose_name='Logros alcanzados')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, help_text='Dejar en blanco si es empleo actual', null=True, verbose_name='Fecha de finalización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('job_title_id', models.ForeignKey(blank=True, db_column='job_title_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.jobtitle', verbose_name='Puesto de Trabajo')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Experiencia Laboral',
                'verbose_name_plural': 'Experiencias Laborales',
                'db_table': 'work_experiences',
                'ordering': ['-start_date', 'user_id'],
            },
        ),
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('user_language_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('level', models.CharField(help_text='Ej: Nativo, Avanzado, Intermedio, Básico', max_length=50, verbose_name='Nivel de dominio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('language_id', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.PROTECT, to='core.languages', verbose_name='Idioma')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_languages', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Idioma de Usuario',
                'verbose_name_plural': 'Idiomas de Usuarios',
                'db_table': 'user_language',
                'unique_together': {('user_id', 'language_id')},
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('user_skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('level', models.CharField(help_text='Ej: Principiante, Intermedio, Avanzado, Experto', max_length=50, verbose_name='Nivel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('skill_id', models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.PROTECT, to='core.skill', verbose_name='Habilidad')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Habilidad de Usuario',
                'verbose_name_plural': 'Habilidades de Usuarios',
                'db_table': 'user_skill',
                'unique_together': {('user_id', 'skill_id')},
            },
        ),
    ]
